/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { Strings, StringsInterface } from "../../Confirmcode.sol/Strings.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "value",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "length",
        "type": "uint256"
      }
    ],
    "name": "StringsInsufficientHexLength",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StringsInvalidAddressFormat",
    "type": "error"
  },
  {
    "inputs": [],
    "name": "StringsInvalidChar",
    "type": "error"
  }
] as const;

  const _bytecode = "0x60556032600b8282823980515f1a607314602657634e487b7160e01b5f525f60045260245ffd5b305f52607381538281f3fe730000000000000000000000000000000000000000301460806040525f5ffdfea26469706673582212206ecd47a7fff4b3c4a750765924755bd5b7d1036cbfb78a44c82a9a75da5cdb5a64736f6c634300081c0033";

  
      type StringsConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: StringsConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class Strings__factory extends ContractFactory {
    
      constructor(...args: StringsConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<Strings & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): Strings__factory {
      return super.connect(runner) as Strings__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): StringsInterface {
      return new Interface(_abi) as StringsInterface;
    }
    
    override attach(address: string | Addressable): Strings {
      return super.attach(address) as Strings;
    }
  static connect(address: string, runner?: ContractRunner | null): Strings {
      return new Contract(address, _abi, runner) as unknown as Strings;
    }
  }

  
  