/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as confirmcodeSol from './Confirmcode.sol/index.js';
export type { confirmcodeSol };
export type { AutomatedPayroll } from './AutomatedPayroll.js';
export type { Counter } from './Counter.js';
export * as factories from './factories/index.js';
export { AutomatedPayroll__factory } from './factories/AutomatedPayroll__factory.js';
export type { ERC165 } from './Confirmcode.sol/ERC165.js';
export { ERC165__factory } from './factories/Confirmcode.sol/ERC165__factory.js';
export type { ERC721 } from './Confirmcode.sol/ERC721.js';
export { ERC721__factory } from './factories/Confirmcode.sol/ERC721__factory.js';
export type { IERC1155Errors } from './Confirmcode.sol/IERC1155Errors.js';
export { IERC1155Errors__factory } from './factories/Confirmcode.sol/IERC1155Errors__factory.js';
export type { IERC165 } from './Confirmcode.sol/IERC165.js';
export { IERC165__factory } from './factories/Confirmcode.sol/IERC165__factory.js';
export type { IERC20Errors } from './Confirmcode.sol/IERC20Errors.js';
export { IERC20Errors__factory } from './factories/Confirmcode.sol/IERC20Errors__factory.js';
export type { IERC721 } from './Confirmcode.sol/IERC721.js';
export { IERC721__factory } from './factories/Confirmcode.sol/IERC721__factory.js';
export type { IERC721Errors } from './Confirmcode.sol/IERC721Errors.js';
export { IERC721Errors__factory } from './factories/Confirmcode.sol/IERC721Errors__factory.js';
export type { IERC721Metadata } from './Confirmcode.sol/IERC721Metadata.js';
export { IERC721Metadata__factory } from './factories/Confirmcode.sol/IERC721Metadata__factory.js';
export type { IERC721Receiver } from './Confirmcode.sol/IERC721Receiver.js';
export { IERC721Receiver__factory } from './factories/Confirmcode.sol/IERC721Receiver__factory.js';
export type { Lollypop } from './Confirmcode.sol/Lollypop.js';
export { Lollypop__factory } from './factories/Confirmcode.sol/Lollypop__factory.js';
export type { Ownable } from './Confirmcode.sol/Ownable.js';
export { Ownable__factory } from './factories/Confirmcode.sol/Ownable__factory.js';
export type { SafeCast } from './Confirmcode.sol/SafeCast.js';
export { SafeCast__factory } from './factories/Confirmcode.sol/SafeCast__factory.js';
export type { Strings } from './Confirmcode.sol/Strings.js';
export { Strings__factory } from './factories/Confirmcode.sol/Strings__factory.js';
export { Counter__factory } from './factories/Counter__factory.js';