/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as confirmcodeSol from './Confirmcode.sol/index.js';
export { AutomatedPayroll__factory } from './AutomatedPayroll__factory.js';
export { Counter__factory } from './Counter__factory.js';
export { Lollypop__factory } from './Lollypop__factory.js';