/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC165 } from './ERC165.js';
export type { ERC721 } from './ERC721.js';
export type { IERC1155Errors } from './IERC1155Errors.js';
export type { IERC165 } from './IERC165.js';
export type { IERC20Errors } from './IERC20Errors.js';
export type { IERC721 } from './IERC721.js';
export type { IERC721Errors } from './IERC721Errors.js';
export type { IERC721Metadata } from './IERC721Metadata.js';
export type { IERC721Receiver } from './IERC721Receiver.js';
export type { Lollypop } from './Lollypop.js';
export type { Ownable } from './Ownable.js';
export type { SafeCast } from './SafeCast.js';
export type { Strings } from './Strings.js';